= An Operator for Automated Certificate Lifecycle in OpenShift
:toc: macro

toc::[]

== Prerequisites

* link:https://github.com/operator-framework/operator-sdk/tree/v0.0.6[Operator SDK v0.0.6]
* link:https://golang.github.io/dep/docs/installation.html[Dep]

== Installation

[source,bash]
----
git clone [this repo]
dep ensure
----

== Local Run for Development

[source,bash]
----
oc login ...
oc new-project cert-operator
oc process -f deploy/rbac.yaml -p NAMESPACE=cert-operator | oc apply -f-
export OPERATOR_NAME=cert-operator
operator-sdk up local
----

== Deployment to OpenShift

[source,bash]
----
oc process -f build/build.yml | oc apply -f-
oc process -f deploy/rbac.yaml -p NAMESPACE=cert-operator | oc apply -f-
oc apply -f deploy/deployment.yaml
----

== Configuration

The operator is configured via a combination of environment variables and a configuration file. The majority of the config can be placed in a `YAML` formatted config file. The configuration file is loaded by searching in the following locations, with those at the top taking priority:

* value of `CERT_OP_CONFIG` environment variable
* `/etc/cert-operator/config.yml`

=== General Config

The cert operator uses annotations on the various resources it manages to decide what actions are required. The annotations that are used are configurable via the config file. The default values are as follows:

[source,yaml]
----
general:
  annotations:
    status: openshift.io/cert-ctl-status
    status-reason: openshift.io/cert-ctl-status-reason
    expiry: openshift.io/cert-ctl-expires
    format: openshift.io/cert-ctl-format
----

=== Certificate Providers

The cert operator provides a pluggable architecture for supporting multiple certificate providers. The following is the set of current and planned providers.

.Supported Providers
* [x] NoneProvider(`none`) - A mock provider for testing which returns empty values
* [x] SelfSignedProvider(`self-signed`) - Delivers self-signed certificates
* [ ] LetsEncryptProvider(`lets-encrpyt`) - A free and open public CA
* [ ] FreeIPAProvider(`ipa`) - An open source identity management system
* [X] VenafiProvider(`venafi`) - An Enterprise PKI product

Configuring which provider is used is a matter of adding the following to your config.yml:

[source,yaml]
----
provider:
  kind: <name>
  ssl: <true/false>
----

=== Notifications

This operator currently supports sending notifications via ChatOps. The following is the set of current and planned providers.

.Supported Notifiers
* [x] Slack
* [ ] RocketChat

To configure sending notifications, set the following environment variables:

[source,bash]
----
NOTIFIER_TYPE="slack"
<NOTIFIER>_WEBHOOK_URL="https://example.webhook.com/bla/blah"
----

== Testing Functionality

This operator will create certificates for routes and services. To test this functionality, first create a new application.

[source,bash]
----
oc new-app --template dotnet-example
----

=== Create a Certificate for a Route

Annotate the route to tell the operator it needs a cert.

[source,bash]
----
oc annotate route dotnet-example openshift.io/cert-ctl-status=new --overwrite
----

In the logs for your operator, you'll see something like:

[source,bash]
----
INFO[0007] Found a route waiting for a cert : sbx-esauer/dotnet-example
INFO[0007] Update route sbx-esauer/dotnet-example with new certificate
----

Then, if you take a look at your `dotnet-example` route, you'll see that it has been update with a TLS Edge policy.

[source,bash]
----
$ oc get route dotnet-example -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/managed.cert: "no"
...
  name: dotnet-example
spec:
...
  tls:
    certificate: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
    termination: edge
    ...
----

=== Create a Certificate for a Service (SSL-to-Pod)

Annotate the service to tell the operator it needs a cert.

[source,bash]
----
oc annotate service dotnet-example openshift.io/cert-ctl-status=new --overwrite
----

In the logs for your operator, you'll see something like:

[source,bash]
----
INFO[0005] Found a service waiting for a cert : sbx-esauer/dotnet-example
INFO[0006] Provisioned new secret sbx-esauer/dotnet-example-certificate containing certificate
INFO[0006] Updated service sbx-esauer/dotnet-example with new certificate
----

Look to see that a new secret has been created in your project.

[source,bash]
----
$ oc get secret | grep dotnet-example
dotnet-example-certificate             Opaque                                2         23m
----

You'll also notice that the annotation on the service has changed.

[source,bash]
----
$ oc get service dotnet-example -o jsonpath='{.metadata.annotations.openshift\.io/cert-ctl-status}'
no
----
