apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
  name: cert-operator
  labels:
    app: cert-operator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cert-operator
      deployment: cert-operator
  template:
    metadata:
      labels:
        app: cert-operator
        deployment: cert-operator
    spec:
      containers:
        - name: cert-operator
          image: docker-registry.default.svc:5000/cert-operator/cert-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cert-operator"
      serviceAccountName: cert-operator
